name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: margam-niranjan
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push Animation to Output Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output  # This keeps changes separate from the main branch
          folder: dist  # The folder where the snake animation is saved
          token: ${{ secrets.GITHUB_TOKEN }}
